# Generated by Django 3.0.8 on 2020-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeritem', '0002_stock_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='counting',
            field=models.CharField(choices=[('Available', 'Available'), ('Given', 'Given')], default='Available', max_length=200),
        ),
    ]
