# Generated by Django 3.0.8 on 2020-08-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeritem', '0004_auto_20200806_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registeritem.Stock'),
        ),
    ]
